### ISSUE TITLE
VK API 2.2.0

### ISSUE THREAD

**Issue by BIITB** [dmitriybakunovich/ExampleWorkVK#2]
Привет, недавно sdk Вконтакте для Android было обновлено, в результате этого изменилась структура sdk и стали недоступны модели. Не мог бы ты пожалуйста переписать этот пример для новой версии sdk, в частности хотелось бы посмотреть как организовать работу с VK.execute(); на Java.

**Comment by DmeetyXC** [comment]
Привет, этот пример уже действительно очень старый и неактуален. Я уже давно не работал с sdk Вконтакте. У них есть репозиторий с подробным описанием последовательности действий для работы с sdk https://github.com/VKCOM/vk-android-sdk. Работа с VK.execute описана в разделе API Requests. Однако данный пример написан на языке Kotlin. Если очень нужно перевести данный пример на Java, я могу помочь в этом, но все же советую попробовать его на Kotlin.
